### ISSUE TITLE
Deploy To Itch.IO CI Scripts Are Not Deploying Anything

### ISSUE THREAD

**Issue by JimLynchCodes** [TheBevyFlock/bevy_new_2d#314]
Hi, thanks for making this starter project! 🙏

I just scaffolded a new project with the command `cargo generate TheBevyFlock/bevy_quickstart`, following along with the YouTube video...

I added my itch.io username, url when creating the project, and I added my itch.io key to Github.

When I push a new tag the build succeeds.

![Screenshot 2024-10-02 at 2 02 12 PM](https://github.com/user-attachments/assets/88a82af9-3435-40d1-bea6-8a11b7e86edb)

But back on itch.io it never shows my game...

![Screenshot 2024-10-02 at 2 02 04 PM](https://github.com/user-attachments/assets/aca2c279-1322-4fa4-8c92-dd5985721338)

What am I doing wrong here? 🤔

My code: https://github.com/JimLynchCodes/ducks-test

Thanks!

**Comment by benfrankel** [comment]
Click on `Edit Project` in the top left and you should see all the uploads there. You have to set the web upload to "This file will be played in the browser". See https://github.com/TheBevyFlock/bevy_new_2d/blob/main/docs/workflows.md.
